### ISSUE TITLE
Api-Design

### ISSUE THREAD

**Issue by MoKob** [mapbox/nepomuk#40]
To get a better impression of how this project will integrate with directions, I though I might start of a discussion by providing my ideas, now including feedback from @freenerd . Still only temporary, though.

*Compatibility*
 - we should aim for compatibility with the osrm/api-directions api, where appropriate. This means we keep the general structure of route/leg separation. We will not try and force data into fields that don't belong.
 - While the general structure of route + legs will look similar, we will add a new meaning to the part leg. In driving directions a leg corresponds to a single waypoint. In our setting, we will have sublegs for every leg between two waypoints. These sublegs will represent a walking leg / a transit line taken without transfer. Transfers will occur between sublegs.
 - we will skip on walking directions and only provide geometry. Since our walking guidance has been neglected a bit (bad me, bad), we will only provide the bare necessity in transit. When needed, we offer a walking API that can be used to get the walking directions.
 - same url format: `https://api-directions/route/v1/transit/-1.4676167,52.4343759;-1.5620915,52.407653?params`. This keeps the general API similar, while requiring new/different options from the standard OSRM format.
 - every subleg will offer it's own mode (this is similar to the turn instructions in osrm, each of which defines a subleg with a series of intersections all with the same mode).

See #47 for a few examples and closer details.

<img width="559" alt="screen shot 2017-03-14 at 09 54 10" src="https://cloud.githubusercontent.com/assets/12932279/23892766/3c969bc2-089c-11e7-819f-c365c5f84fa3.png">

The image illustrates start/stop (coordinates), walking segments (green), even in between: basic transfer, with instructions if possible., and different transportation modes (bus / train).
This trip would consist of 5 legs, walking in begin / end, 1 bus ride, 1 transfer, 1 train tride.

## Possible Parameters

options should be used to specify the additional required transit parameters

 - depart -- when to depart (UTC timestamp) mutually exclusive to arrive
 - arrive -- when to arrive (mutually exclusive to depart)
 - layover -- array of durations specifying layovers for via coordinates
 - transfer -- slow / normal / quick (hint to how much time is required on transfers)
 - alternatives -- report a set of multiple choices (e.g. hops, price, time, different routes)
 - avoid -- don't use bus/train/ferry 

# Tasks

_In/Before Discussion_
 - [ ] flesh out possible parameter section
 - [ ] closer define how steps would look like

_After Discussion_
 - [ ] output a valid osrm-json / api-directions json to integrate into existing frontends
 - [ ] augment frontend to create a mock-up for easy testing (searching for current time)
